- name: Downloading consul
  unarchive:
    src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
    dest: /tmp
    remote_src: yes
  register: download
  until: download is succeeded
  retries: 99
  delay: 3
  delegate_to: localhost
  become: no
  run_once: yes

- name: Copy the /tmp/consul into downloaded_files
  copy:
    src: /tmp/consul
    dest: "downloaded_files/consul-{{ consul_version }}"
  delegate_to: localhost
  become: no
  run_once: yes
