- block:
    - name: checking consul command
      shell: /usr/local/bin/consul version | head -n1 | awk '{ gsub("v","") ; print $2 }'
      register: verChk
      changed_when: false
      failed_when: verChk.stdout is version(consul_version, operator='lt', strict=True)
    - name: checking consul port
      wait_for:
        host: 0.0.0.0
        port: 8600
        timeout: 3
  rescue:
    - include_tasks: install.yml

- include_tasks: config.yml
# - include_tasks: resolv.yml
