- name: checking if target is suitable for deploy
  assert:
    that:
      - "ansible_memtotal_mb|int >= {{ env_check_memtotal_mb|default('1024')|int }}"
      - "ansible_memory_mb.nocache.free|int >= {{ env_check_memory_mb_nocache_free|default('1024')|int }}"
      - "ansible_processor_vcpus|int >= {{ env_check_processor_vcpus|default('1')|int }}"
      - "ansible_architecture == 'x86_64'"
  when: "'elasticsearch' in group_names"

- name: 'check if port {{ elastic_http_port }} available'
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_' + bond_interface]['ipv4']['address'] }}"
    port: '{{ elastic_http_port }}'
    state: stopped
    timeout: 3
  register: portSt

- name: Config limit.conf
  lineinfile:
    path: /etc/security/limits.conf
    line: '{{ item }}'
  with_items:
    - 'elasticsearch soft memlock unlimited'
    - 'elasticsearch hard memlock unlimited'
    - 'elasticsearch - nofile 65536'
    - 'ulimit -n 65536'
    - 'fsize unlimited'
