actions:
  1:
    action: allocation
    description: "Apply shard allocation filtering rules to the specified indices"
    options:
      key: box_type
      value: warm
      allocation_type: require
      wait_for_completion: true
      timeout_override:
      continue_if_exception: false
      disable_action: false
    filters:
    - filtertype: pattern
      kind: prefix
      value: (logstash|filebeat|metricbeat|packetbeat)-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 3
  2:
      action: forcemerge
      description: "Perform a forceMerge on selected indices to 'max_num_segments' per shard"
      options:
        max_num_segments: 1
        delay:
        timeout_override: 21600
        continue_if_exception: false
        disable_action: false
      filters:
      - filtertype: pattern
        kind: prefix
        value: (logstash|filebeat|metricbeat|packetbeat)-
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: 3
