- block:
    - name: 'uploading packages'
      copy:
        src: 'downloaded_files/{{ item }}.deb'
        dest: /tmp/
      with_items:
        - libjemalloc1_3.6.0-9ubuntu1_amd64
        - redis-tools_3.0.6-1_amd64
        - redis-server_3.0.6-1_amd64
        - redis-sentinel_3.0.6-1_amd64
    - name: 'installing packages'
      apt:
        deb: '/tmp/{{ item }}.deb'
      with_items:
        - libjemalloc1_3.6.0-9ubuntu1_amd64
        - redis-tools_3.0.6-1_amd64
        - redis-server_3.0.6-1_amd64
        - redis-sentinel_3.0.6-1_amd64
  rescue:
    - include_tasks: download.yml format=deb
    - include_tasks: '{{ ansible_os_family }}.yml'
  always:
    - name: 'removing packages'
      file:
        path: '/tmp/{{ item }}.deb'
        state: absent
      with_items:
        - redis-tools_3.0.6-1_amd64
        - libjemalloc1_3.6.0-9ubuntu1_amd64
        - redis-server_3.0.6-1_amd64
        - redis-sentinel_3.0.6-1_amd64
